### PR TITLE
Mark 3.4.3

### PR DESCRIPTION
**Pull request by ColdHeat**
# 3.4.3 / 2022-03-07

**Security**

- Bump cmarkgfm to 0.8.0 to resolve CVE-2022-24724. Copied entry from 3.4.2 since 3.4.2 introduced a bug that prevented writing raw HTML.

**General**

- Fix issue where raw HTML would not be rendered in markdown

### CODE REVIEW

**Comment by joevin-slq** [comment]
Hello @ColdHeat,

I've got this after updating from 3.0 to 3.4.3.

`
ctfd-core | 172.18.0.7 - - [14/Mar/2022:11:42:43 +0000] "GET //api/v1/challenges/69 HTTP/1.0" 200 5519 "https://vps635492.ovh.net/ctfd/challenges" "Mozilla/5.0 (X11; Linux x86_64; rv:97.0) Gecko/20100101 Firefox/97.0"
ctfd-core | ERROR [CTFd] Exception on /ctfd/api/v1/hints/69 [GET]
ctfd-core | Traceback (most recent call last):
ctfd-core |   File "/usr/local/lib/python3.7/site-packages/marshmallow/schema.py", line 832, in __filter_fields
ctfd-core |     attribute_type = type(getattr(obj, key))
ctfd-core |   File "/opt/CTFd/CTFd/models/__init__.py", line 170, in html
ctfd-core |     return markup(build_markdown(self.content))
ctfd-core |   File "/opt/CTFd/CTFd/utils/config/pages.py", line 45, in build_markdown
ctfd-core |     html = markdown(md)
ctfd-core |   File "/opt/CTFd/CTFd/utils/__init__.py", line 20, in markdown
ctfd-core |     options=Options.CMARK_OPT_UNSAFE,
ctfd-core | AttributeError: type object 'Options' has no attribute 'CMARK_OPT_UNSAFE'
ctfd-core | 
ctfd-core | During handling of the above exception, another exception occurred:
ctfd-core | 
ctfd-core | Traceback (most recent call last):
ctfd-core |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
ctfd-core |     rv = self.dispatch_request()
ctfd-core |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
ctfd-core |     return self.view_functions[rule.endpoint](**req.view_args)
ctfd-core |   File "/usr/local/lib/python3.7/site-packages/flask_restx/api.py", line 403, in wrapper
ctfd-core |     resp = resource(*args, **kwargs)
ctfd-core |   File "/usr/local/lib/python3.7/site-packages/flask/views.py", line 89, in view
ctfd-core |     return self.dispatch_request(*args, **kwargs)
ctfd-core |   File "/usr/local/lib/python3.7/site-packages/flask_restx/resource.py", line 49, in dispatch_request
ctfd-core |     resp = meth(*args, **kwargs)
ctfd-core |   File "/opt/CTFd/CTFd/utils/decorators/__init__.py", line 23, in during_ctf_time_only_wrapper
ctfd-core |     return f(*args, **kwargs)
ctfd-core |   File "/opt/CTFd/CTFd/utils/decorators/__init__.py", line 87, in authed_only_wrapper
ctfd-core |     return f(*args, **kwargs)
ctfd-core |   File "/opt/CTFd/CTFd/api/v1/hints.py", line 136, in get
ctfd-core |     response = HintSchema(view=view).dump(hint)
ctfd-core |   File "/usr/local/lib/python3.7/site-packages/marshmallow/schema.py", line 508, in dump
ctfd-core |     self._update_fields(processed_obj, many=many)
ctfd-core |   File "/usr/local/lib/python3.7/site-packages/marshmallow/schema.py", line 771, in _update_fields
ctfd-core |     ret = self.__filter_fields(field_names, obj, many=many)
ctfd-core |   File "/usr/local/lib/python3.7/site-packages/marshmallow/schema.py", line 836, in __filter_fields
ctfd-core |     '"{0}" is not a valid field for {1}.'.format(key, obj))
ctfd-core | AttributeError: "html" is not a valid field for <Hint 'Try to find a reference or clue behind the scenes. Or simply guess what URL the Score Board might have.'>.
ctfd-core | 172.18.0.7 - - [14/Mar/2022:11:42:47 +0000] "GET //api/v1/hints/69 HTTP/1.0" 500 37 "https://vps635492.ovh.net/ctfd/challenges" "Mozilla/5.0 (X11; Linux x86_64; rv:97.0) Gecko/20100101 Firefox/97.0"
`

There is a problem with cmarkgfm update.

**Comment by ColdHeat** [comment]
@joevin-slq did you run `pip install --upgrade -r requirements.txt`? Can you check what cmarkgfm version you are running?
